all: insn_add_ch0 insn_addi_ch0 insn_and_ch0 insn_andi_ch0 insn_beq_ch0 insn_jal_ch0 insn_lw_ch0 insn_or_ch0 insn_ori_ch0 insn_slt_ch0 insn_slti_ch0 insn_sub_ch0 insn_sw_ch0 reg_ch0 pc_fwd_ch0 cover
insn_add_ch0: ../insn_add_ch0/insn_add_ch0_results.txt
../insn_add_ch0/insn_add_ch0_results.txt:
	vcf -f ../insn_add_ch0/insn_add_ch0.tcl -batch
.PHONY: insn_add_ch0
insn_addi_ch0: ../insn_addi_ch0/insn_addi_ch0_results.txt
../insn_addi_ch0/insn_addi_ch0_results.txt:
	vcf -f ../insn_addi_ch0/insn_addi_ch0.tcl -batch
.PHONY: insn_addi_ch0
insn_and_ch0: ../insn_and_ch0/insn_and_ch0_results.txt
../insn_and_ch0/insn_and_ch0_results.txt:
	vcf -f ../insn_and_ch0/insn_and_ch0.tcl -batch
.PHONY: insn_and_ch0
insn_andi_ch0: ../insn_andi_ch0/insn_andi_ch0_results.txt
../insn_andi_ch0/insn_andi_ch0_results.txt:
	vcf -f ../insn_andi_ch0/insn_andi_ch0.tcl -batch
.PHONY: insn_andi_ch0
insn_beq_ch0: ../insn_beq_ch0/insn_beq_ch0_results.txt
../insn_beq_ch0/insn_beq_ch0_results.txt:
	vcf -f ../insn_beq_ch0/insn_beq_ch0.tcl -batch
.PHONY: insn_beq_ch0
insn_jal_ch0: ../insn_jal_ch0/insn_jal_ch0_results.txt
../insn_jal_ch0/insn_jal_ch0_results.txt:
	vcf -f ../insn_jal_ch0/insn_jal_ch0.tcl -batch
.PHONY: insn_jal_ch0
insn_lw_ch0: ../insn_lw_ch0/insn_lw_ch0_results.txt
../insn_lw_ch0/insn_lw_ch0_results.txt:
	vcf -f ../insn_lw_ch0/insn_lw_ch0.tcl -batch
.PHONY: insn_lw_ch0
insn_or_ch0: ../insn_or_ch0/insn_or_ch0_results.txt
../insn_or_ch0/insn_or_ch0_results.txt:
	vcf -f ../insn_or_ch0/insn_or_ch0.tcl -batch
.PHONY: insn_or_ch0
insn_ori_ch0: ../insn_ori_ch0/insn_ori_ch0_results.txt
../insn_ori_ch0/insn_ori_ch0_results.txt:
	vcf -f ../insn_ori_ch0/insn_ori_ch0.tcl -batch
.PHONY: insn_ori_ch0
insn_slt_ch0: ../insn_slt_ch0/insn_slt_ch0_results.txt
../insn_slt_ch0/insn_slt_ch0_results.txt:
	vcf -f ../insn_slt_ch0/insn_slt_ch0.tcl -batch
.PHONY: insn_slt_ch0
insn_slti_ch0: ../insn_slti_ch0/insn_slti_ch0_results.txt
../insn_slti_ch0/insn_slti_ch0_results.txt:
	vcf -f ../insn_slti_ch0/insn_slti_ch0.tcl -batch
.PHONY: insn_slti_ch0
insn_sub_ch0: ../insn_sub_ch0/insn_sub_ch0_results.txt
../insn_sub_ch0/insn_sub_ch0_results.txt:
	vcf -f ../insn_sub_ch0/insn_sub_ch0.tcl -batch
.PHONY: insn_sub_ch0
insn_sw_ch0: ../insn_sw_ch0/insn_sw_ch0_results.txt
../insn_sw_ch0/insn_sw_ch0_results.txt:
	vcf -f ../insn_sw_ch0/insn_sw_ch0.tcl -batch
.PHONY: insn_sw_ch0
reg_ch0: ../reg_ch0/reg_ch0_results.txt
../reg_ch0/reg_ch0_results.txt:
	vcf -f ../reg_ch0/reg_ch0.tcl -batch
.PHONY: reg_ch0
pc_fwd_ch0: ../pc_fwd_ch0/pc_fwd_ch0_results.txt
../pc_fwd_ch0/pc_fwd_ch0_results.txt:
	vcf -f ../pc_fwd_ch0/pc_fwd_ch0.tcl -batch
.PHONY: pc_fwd_ch0
cover: ../cover/cover_results.txt
../cover/cover_results.txt:
	vcf -f ../cover/cover.tcl -batch
.PHONY: cover
